# Enhanced Mushroom Cards YAML Examples
# Two new custom cards: Split Layout and Enhanced Light with Popup

# =====================================
# SPLIT LAYOUT CARD - 28%/72% Dashboard
# =====================================

# Basic Split Layout
- type: custom:mushroom-split-layout-card
  sidebar:
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: markdown
        content: |
          ## Quick Info
          Sidebar content here
  main:
    cards:
      - type: custom:mushroom-enhanced-light-card
        entity: light.living_room
      - type: picture-entity
        entity: camera.front_door

# Split Layout with Background Colors/Images
- type: custom:mushroom-split-layout-card
  sidebar_width: 30              # Custom width (default: 28)
  gap: 16                        # Custom gap (default: 12px)
  sidebar:
    background_color: "#f5f5f5"   # Light gray background
    background_image: "/local/images/sidebar-bg.jpg"  # Optional background image
    cards:
      - type: custom:mushroom-enhanced-light-card
        entity: light.bedroom
        button_layout: vertical-enhanced
  main:
    background_color: "#ffffff"   # White background
    cards:
      - type: markdown
        content: |
          ## Main Dashboard
          72% width content area
      - type: entities
        entities:
          - light.living_room
          - light.kitchen

# =====================================
# ENHANCED LIGHT CARD WITH POPUP
# =====================================

# Enhanced Light Card with Custom Popup
- type: custom:mushroom-enhanced-light-card
  entity: light.living_room_group
  name: Living Room Lights
  
  # Layout Options
  button_layout: vertical-enhanced    # "inline" or "vertical-enhanced"
  font_size: 16                      # Text size in pixels
  icon_offset_x: 20                  # Move icon/text right by pixels
  text_align: center                 # "left", "center", "right"
  show_brightness_percentage: false   # Hide percentage text
  
  # Standard Mushroom Controls
  show_brightness_control: true
  show_color_temp_control: true
  show_color_control: true
  collapsible_controls: false
  
  # Enhanced Popup Configuration
  double_tap_action:
    action: enhanced-more-info        # Trigger custom popup
  enhanced_popup:
    show_sub_entities: true           # Show individual lights in group
    show_effects: true                # Show effect dropdown
    show_scenes: false                # Show scene buttons (future)
    show_advanced_controls: true      # Show more-info/settings buttons

# Enhanced Light Card - Horizontal Layout
- type: custom:mushroom-enhanced-light-card
  entity: light.kitchen
  button_layout: inline              # Buttons right of slider
  font_size: 14
  text_align: left
  show_brightness_percentage: true
  hold_action:
    action: enhanced-more-info        # Long press for popup

# Enhanced Light Card - Custom Styling
- type: custom:mushroom-enhanced-light-card
  entity: light.bedroom
  button_layout: vertical-enhanced
  font_size: 18
  icon_offset_x: 30
  text_align: center
  show_brightness_percentage: false
  
  # Custom colors (standard Mushroom theming)
  icon_color: blue
  use_light_color: true
  
  # Enhanced popup with minimal options
  tap_action:
    action: enhanced-more-info
  enhanced_popup:
    show_sub_entities: false
    show_effects: true
    show_advanced_controls: false

# =====================================
# DASHBOARD VIEW EXAMPLES
# =====================================

# Panel View with Split Layout (Recommended)
views:
  - title: Custom Dashboard
    path: custom-dash
    panel: true                      # Important: Use panel mode
    cards:
      - type: custom:mushroom-split-layout-card
        sidebar_width: 28
        sidebar:
          background_color: "rgba(0,0,0,0.05)"
          cards:
            - type: custom:mushroom-enhanced-light-card
              entity: light.hallway
              button_layout: vertical-enhanced
              font_size: 14
            - type: weather-forecast
              entity: weather.home
        main:
          cards:
            - type: horizontal-stack
              cards:
                - type: custom:mushroom-enhanced-light-card
                  entity: light.living_room
                  button_layout: inline
                - type: custom:mushroom-enhanced-light-card
                  entity: light.kitchen  
                  button_layout: inline

# Regular View with Enhanced Light Cards
  - title: Enhanced Lights
    path: enhanced-lights
    cards:
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:mushroom-enhanced-light-card
            entity: light.living_room
            button_layout: vertical-enhanced
            double_tap_action:
              action: enhanced-more-info
          - type: custom:mushroom-enhanced-light-card
            entity: light.bedroom
            button_layout: vertical-enhanced
            hold_action:
              action: enhanced-more-info

# =====================================
# KEY FEATURES SUMMARY
# =====================================

# Split Layout Card:
# - Fixed 28%/72% or custom width split
# - Background colors and images
# - Drag-and-drop UI support (via HA dashboard editor)
# - YAML configuration support
# - Responsive design (stacks on mobile)

# Enhanced Light Card:
# - All original Mushroom features
# - Custom popup instead of default more-info
# - Vertical button layout option
# - Font size and positioning controls
# - Text alignment options
# - Commands only sent on slider release (no spam)
# - Enhanced color temperature gradient

# Deployment:
# 1. Copy dist/mushroom.js to /config/www/mushroom-dev/
# 2. Add resource: /local/mushroom-dev/loader.js?v=dev
# 3. Use the YAML examples above in your dashboards
