title: Split Layout Demo
views:
  - title: Split Dashboard
    path: split-dashboard
    panel: true                    # CRITICAL: Makes the card span entire view
    cards:
        - type: custom:mushroom-split-layout-card
          sidebar_width: 25          # 25% sidebar width
          gap: 20                    # 20px gap between columns
          full_height: true
          full_width: true
          
          # Overall container styling (hotel theme)
          container_style:
            background_color: "#1a1a2e"
            background_image: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)"
            opacity: 1.0
            custom_css: "font-family: 'Segoe UI', system-ui, sans-serif;"
          
          # Logo overlay (top right corner) - fully customizable
          logo:
            image_url: "/local/logo-tot.png"
            position: "top-right"
            width: "150px"                    # Specific width
            height: "auto"                    # Auto height to maintain aspect ratio
            max_width: "150px"                # Maximum width constraint
            max_height: "200px"                # Maximum height constraint
            opacity: 0.9
            margin_top: "100px"                # Distance from top
            margin_right: "25px"              # Distance from right edge
            z_index: 1000
            filter: "drop-shadow(0 3px 6px rgba(0,0,0,0.4)) brightness(1.1)"
            transform: "scale(0.9)"           # Slightly smaller scale
            transition: "all 0.3s ease"       # Smooth transitions
            border_radius: "8px"              # Rounded logo corners
            background_color: "rgba(255,255,255,0.1)"  # Subtle background
            padding: "8px"                    # Padding around logo
          
          # Global card styling - 
          card_style:
            border_radius: "25px"                           # Rounded corners ("0px" for rectangular)
            background_color: "rgba(255, 255, 255, 0.95)"  # Card background color
            background_opacity: 0.9                        # Card transparency
            box_shadow: "0 8px 25px rgba(0, 0, 0, 0.2)"   # Card shadows
            backdrop_filter: "blur(2px) brightness(1.05)"  # Glass effect ✅
            # OUTLINE-BASED BORDERS (grid-safe alternative to border)
            border_width: "2px"                             # Outline thickness ✅
            border_color: "rgba(50, 255, 255, 0.8)"       # Outline color ✅
            border_style: "solid"                          # Outline style ✅ (solid, dashed, dotted)
            backdrop_filter: "blur(5px) brightness(1.1)"  # Glass effect
          
          sidebar:
            background_color: "rgba(255, 255, 255, 0.1)"
            background_image: "linear-gradient(180deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.05) 100%)"
            background_size: "cover"
            background_position: "center"
            opacity: 0.95
            padding: "24px"
            border_radius: "20px"
            border: "1px solid rgba(255, 255, 255, 0.2)"
            box_shadow: "0 8px 32px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.1)"
            overflow: "auto"
            custom_css: "backdrop-filter: blur(10px);"
            cards:
            - type: markdown
              content: |
                ## Sidebar Controls
                This is your 28% sidebar area
          main:
            background_color: "rgba(255, 255, 255, 0.9)"
            background_image: "linear-gradient(45deg, rgba(255,255,255,0.1) 25%, transparent 25%), linear-gradient(-45deg, rgba(255,255,255,0.1) 25%, transparent 25%)"
            background_size: "20px 20px"
            background_position: "0 0, 0 10px"
            opacity: 0.98
            padding: "32px"
            border_radius: "15px"
            border: "1px solid rgba(255, 255, 255, 0.3)"
            box_shadow: "0 4px 20px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.3)"
            overflow: "auto"
            custom_css: "backdrop-filter: blur(5px); transition: all 0.3s ease;"
            cards:
            # Top row - full width header
            - type: markdown
              content: |
                # Main Dashboard
                This is your 72% main content area
            
            # Multiple columns using horizontal-stack with vertical-stacks (independent heights)
            - type: horizontal-stack
              cards:
                # Column 1 - Independent height
                - type: vertical-stack
                  cards:
                    # Original Mushroom Light Card (for comparison)
                    - type: custom:mushroom-light-card
                      entity: light.ceiling_lights
                      name: "Original Mushroom"
                      show_brightness_control: true
                      show_color_temp_control: true
                      show_color_control: true
                      collapsible_controls: false
                      double_tap_action:
                        action: more-info
                    
                    # Add more cards to first column to test height
                    - type: custom:mushroom-light-card
                      entity: light.ceiling_lights
                      name: "Small Card 1"
                      show_brightness_control: false
                      show_color_temp_control: false
                      show_color_control: false
                    
                    - type: custom:mushroom-light-card
                      entity: light.ceiling_lights
                      name: "Small Card 2"
                      show_brightness_control: false
                      show_color_temp_control: false
                      show_color_control: false
                    
                    - type: custom:mushroom-light-card
                      entity: light.ceiling_lights
                      name: "Small Card 3"
                      show_brightness_control: false
                      show_color_temp_control: false
                      show_color_control: false
                    
                    - type: custom:mushroom-light-card
                      entity: light.ceiling_lights
                      name: "Small Card 4"
                      show_brightness_control: false
                      show_color_temp_control: false
                      show_color_control: false
                
                # Column 2 - Independent height
                - type: vertical-stack
                  cards:
                    # Enhanced Light Card with Custom Styling
                    - type: custom:mushroom-enhanced-light-card
                      entity: light.ceiling_lights
                      name: "Enhanced Card"
                      button_layout: vertical-enhanced
                      font_size: 25
                      text_align: center
                      icon_offset_x: 5
                      show_brightness_control: true
                      show_color_temp_control: true
                      show_color_control: true
                      collapsible_controls: false
                      # New styling options test
                      card_background_color: "#e3f2fd"     # Light blue background
                      card_border_color: "#f44336"         # Red border
                      card_border_width: "1px"             # 3px border width
                      card_border_radius: "50px"           # Rounded corners
                      card_box_shadow: "0 4px 12px rgba(244, 67, 54, 0.3)"  # Red shadow
                      
                      double_tap_action:
                        action: enhanced-more-info
                      enhanced_popup:
                        show_sub_entities: true
                        show_effects: true
                        show_advanced_controls: true
                        card_type: mushroom
                        title: "Light Control Center"
                        background_color: "#f0f0f0"
                        sub_entities_text: "If a light didn't react properly, please click here the light that is still on."
                        text_style:
                          font_size: "16px"
                          font_weight: "500"
                          color: "#856404"
                          background_color: "#fff3cd"
                          text_align: "center"
                          padding: "16px 20px"
                          border_radius: "12px"
                
                # Column 3 - Independent height
                - type: vertical-stack
                  cards:
                    # Standard entities card for reference
                    - type: entities
                      title: Quick Controls
                      entities:
                        - light.ceiling_lights
                        - input_boolean.lobby
                        - sensor.room_temperature
            
            # Another row with 3 columns
            - type: grid
              columns: 3              # 3 columns
              square: false
              cards:
                # Test card with background image (full opacity first - should work)
                - type: custom:mushroom-enhanced-light-card
                  entity: light.ceiling_lights
                  name: "Background Image"
                  button_layout: inline
                  font_size: 14
                  card_background_image: "/local/logo-tot.png"
                  card_background_image_position: "right"   # Position image to the right
                  card_background_color: "#f0f8ff"          # Light background behind image
                  card_border_radius: "20px"
                
                # Test card with gradient-like effect using colors
                - type: custom:mushroom-enhanced-light-card
                  entity: light.ceiling_lights
                  name: "Green Theme"
                  button_layout: inline
                  font_size: 14
                  card_background_color: "#e8f5e8"
                  card_border_color: "#4caf50"
                  card_border_width: "2px"
                  card_box_shadow: "0 2px 8px rgba(76, 175, 80, 0.4)"
                
                # Test card with minimal styling
                - type: custom:mushroom-enhanced-light-card
                  entity: light.ceiling_lights
                  name: "Minimal"
                  button_layout: inline
                  font_size: 14
                  card_background_color: "#ffffff"
                  card_border_color: "#e0e0e0"
                  card_border_width: "1px"
                  card_border_radius: "8px"

            # Showcase Row: Vertical-Enhanced Layout Examples with Background Images
            - type: horizontal-stack
              cards:
                # Example 1: Elegant Glass Effect
                - type: custom:mushroom-enhanced-light-card
                  entity: light.ceiling_lights
                  name: "Glass Effect"
                  button_layout: vertical-enhanced
                  font_size: 18
                  text_align: center
                  icon_offset_x: 0
                  show_brightness_control: true
                  show_color_temp_control: true
                  show_color_control: true
                  collapsible_controls: false
                  # Glass-like styling with background image
                  card_background_image: "/local/logo-tot.png"
                  card_background_image_opacity: 0.15
                  card_background_image_position: "center"
                  card_background_color: "rgba(255, 255, 255, 0.9)"
                  card_border_color: "rgba(255, 255, 255, 0.3)"
                  card_border_width: "2px"
                  card_border_radius: "25px"
                  card_box_shadow: "0 8px 32px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.2)"
                  
                  double_tap_action:
                    action: enhanced-more-info
                  enhanced_popup:
                    show_sub_entities: true
                    show_effects: true
                    show_advanced_controls: true
                    card_type: mushroom
                    title: "Glass Effect Light Control"
                    background_color: "rgba(255, 255, 255, 0.95)"
                    sub_entities_text: "Advanced light controls with glass effect styling"
                    text_style:
                      font_size: "14px"
                      color: "#333333"
                      background_color: "rgba(255, 255, 255, 0.8)"
                      padding: "12px"
                      border_radius: "15px"

                # Example 2: Dark Theme with Neon Borders
                - type: custom:mushroom-enhanced-light-card
                  entity: light.ceiling_lights
                  name: "Neon Dark"
                  button_layout: vertical-enhanced
                  font_size: 20
                  text_align: center
                  icon_offset_x: 0
                  show_brightness_control: true
                  show_color_temp_control: true
                  show_color_control: true
                  collapsible_controls: false
                  # Dark theme with neon accent
                  card_background_image: "/local/logo-tot.png"
                  card_background_image_opacity: 0.08
                  card_background_image_position: "right bottom"
                  card_background_color: "#1a1a1a"
                  card_border_color: "#00ffff"
                  card_border_width: "3px"
                  card_border_radius: "15px"
                  card_box_shadow: "0 0 20px rgba(0, 255, 255, 0.3), 0 4px 15px rgba(0, 0, 0, 0.5)"
                  
                  double_tap_action:
                    action: enhanced-more-info
                  enhanced_popup:
                    show_sub_entities: true
                    show_effects: true
                    show_advanced_controls: true
                    card_type: mushroom
                    title: "Neon Light Control"
                    background_color: "#2a2a2a"
                    sub_entities_text: "Cyberpunk-style light controls with neon effects"
                    text_style:
                      font_size: "14px"
                      color: "#00ffff"
                      background_color: "rgba(0, 255, 255, 0.1)"
                      padding: "12px"
                      border_radius: "10px"
                      border: "1px solid rgba(0, 255, 255, 0.3)"

                # Example 3: Warm Gradient Theme
                - type: custom:mushroom-enhanced-light-card
                  entity: light.ceiling_lights
                  name: "Warm Sunset"
                  button_layout: vertical-enhanced
                  font_size: 16
                  text_align: center
                  icon_offset_x: 0
                  show_brightness_control: true
                  show_color_temp_control: true
                  show_color_control: true
                  collapsible_controls: false
                  # Warm gradient theme
                  card_background_image: "/local/logo-tot.png"
                  card_background_image_opacity: 0.25
                  card_background_image_position: "left top"
                  card_background_color: "linear-gradient(135deg, #ff9a56 0%, #ff6b6b 100%)"
                  card_border_color: "#ff6b6b"
                  card_border_width: "2px"
                  card_border_radius: "30px"
                  card_box_shadow: "0 6px 25px rgba(255, 107, 107, 0.4)"
                  
                  double_tap_action:
                    action: enhanced-more-info
                  enhanced_popup:
                    show_sub_entities: true
                    show_effects: true
                    show_advanced_controls: true
                    card_type: mushroom
                    title: "Sunset Light Control"
                    background_color: "#fff5f5"
                    sub_entities_text: "Warm and cozy lighting controls for perfect ambiance"
                    text_style:
                      font_size: "14px"
                      color: "#d63031"
                      background_color: "rgba(255, 107, 107, 0.1)"
                      padding: "14px"
                      border_radius: "20px"
